// src/data/projects.js

const projects = [
  {
    id: 1,
    title: "Conceptual Skyscraper #25",
    year: " 2021",
    image: "/assets/PROJECTSALLPROJECTS/Conceptual Skyscrapers 25/IMG1880.JPG",
    link: "/projects/conceptual-skyscraper25",
  },
  {
    id: 2,
    title: "Condominium Apartment #42",
    year: " 2020",
    image: "/assets/PROJECTSALLPROJECTS/Condominium Apt 42/IMG_2191.JPG",
    link: "/projects/condominium-apartment42",
  },
  {
    id: 3,
    title: "Condominium Karma Residence",
    year: " 2022",
    image: "/assets/PROJECTSALLPROJECTS/Condominium Karma Residence indonesia/PNG image 1.png",
    link: "/projects/condominium-karmaResidence",
  },
  {
    id: 4,
    title: "Farmhouse (Richmond, USA)",
    year: " 2016",
    image: "/assets/PROJECTSALLPROJECTS/Farm house near richmond/PNG IMAGE 01.jpg",
    link: "/projects/farmhouse",
  },
  {
    id: 5,
    title: "Flat Interiors #221",
    year: " 2020",
    image: "/assets/PROJECTSALLPROJECTS/Flat Interiors 221/PNG image 2.png",
    link: "/projects/flatinteriors221",
  },
  {
    id: 6,
    title: "Forest Resort ",
    year: " 2023",
    image: "/assets/PROJECTSALLPROJECTS/Forest Resort/PNG image 2.png",
    link: "/projects/forest-resort-gallery",
  },
  {
    id: 7,
    title: "House CAD",
    year: " 2019",
    image: "/assets/PROJECTSALLPROJECTS/House CAD Brazil/PNG image 2.png",
    link: "/projects/house-cad",
  },
  {
    id: 8,
    title: "House for Staycation ",
    year: " 2021",
    image: "/assets/PROJECTSALLPROJECTS/House for Staycation UK/PNG image 1.png",
    link: "/projects/housefor-staycation",
  },
  {
    id: 9,
    title: "Luxury Gated Community",
    year: " 2022",
    image: "/assets/PROJECTSALLPROJECTS/Luxury Gated Community Giana Capital/PNG image 1.png",
    link: "/projects/luxurygated-community",
  },
  {
    id: 10,
    title: "Mixed Use Apartment (Astralis)",
    year: " 2023",
    image: "/assets/PROJECTSALLPROJECTS/Mixed use Apartment/PNG image 1.png",
    link: "/projects/mixeduse-apartment-astralis",
  },
  {
    id: 11,
    title: "Private Villa",
    year: " 2023",
    image: "/assets/PROJECTSALLPROJECTS/Private Villa USA/PNG image 1.png",
    link: "/projects/privatevilla",
  },
  {
    id: 12,
    title: "Residence #11",
    year: "  2024",
    image: "/assets/PROJECTSALLPROJECTS/Residence 11/PNG image 1.png",
    link: "/projects/residence11",
  },
  {
    id: 13,
    title: "Residence #622",
    year: " 2021",
    image: "/assets/PROJECTSALLPROJECTS/Residence 622/PNG image 2.png",
    link: "/projects/residence622",
  },
  {
    id: 14,
    title: "Residence #7 ",
    year: " 2020",
    image: "/assets/PROJECTSALLPROJECTS/Residence 7/PNG image 1.png",
    link: "/projects/residence7",
  },
  {
    id: 15,
    title: "Sandalwood Villa Interiors",
    year: "Residential 2019",
    image: "/assets/PROJECTSALLPROJECTS/Sandalwood Villa Interiors/PNG image 1.png",
    link: "/projects/sandalwoodvilla",
  },
  {
    id: 16,
    title: "Villa #22",
    year: " 2019",
    image: "/assets/PROJECTSALLPROJECTS/Villa 22/PNG image 1.png",
    link: "/projects/villa22",
  },
  {
    id: 17,
    title: "Villa #44",
    year: " 2023",
    image: "/assets/PROJECTSALLPROJECTS/Villa44 Miami/PNG _mage_1.png",
    link: "/projects/villa44",
  },
  {
    id: 18,
    title: "Villa Entrance",
    year: "  2023",
    image: "/assets/PROJECTSALLPROJECTS/Villa Entrance/PNG image 1.png",
    link: "/projects/villaentrance",
  },
];

export default projects;
