// src/data/projects.js

const projects = [
  {
    id: 1,
    title: "Conceptual Skyscraper #25",
    year: "Residential 2021",
    image: "/assets/PROJECTSALLPROJECTS/Conceptual Skyscrapers 25/IMG  1881.JPG",
    link: "/home",
  },
  {
    id: 2,
    title: "Condominium Apartment #42",
    year: "Condominium 2020",
    image: "/assets/PROJECTSALLPROJECTS/Condominium Apt 42/IMG_2191.JPG",
    link: "/gallery/condo42",
  },
  {
    id: 3,
    title: "Condominium Karma Residence",
    year: "Condominium 2022",
    image: "/assets/PROJECTSALLPROJECTS/Condominium Karma Residence (Indonesia)/PNG image 1.png",
    link: "/gallery/karma-residence",
  },
  {
    id: 4,
    title: "Farmhouse (Richmond, USA)",
    year: "Residential 2016",
    image: "/assets/PROJECTSALLPROJECTS/Farm house near richmond/PNG IMAGE 01.jpg",
    link: "/gallery/farmhouse",
  },
  {
    id: 5,
    title: "Flat Interiors #221",
    year: "Residential 2020",
    image: "/assets/PROJECTSALLPROJECTS/Flat Interiors 221/PNG image 2.png",
    link: "/gallery/flat221",
  },
  {
    id: 6,
    title: "Forest Resort ",
    year: "Hospitality 2023",
    image: "/assets/PROJECTSALLPROJECTS/Forest Resort/PNG image 2.png",
    link: "/gallery/forest-resort",
  },
  {
    id: 7,
    title: "House CAD",
    year: "Residential 2012",
    image: "/assets/PROJECTSALLPROJECTS/House CAD (Brazil)/PNG image 2.png",
    link: "/gallery/house-cad",
  },
  {
    id: 8,
    title: "House for Staycation ",
    year: "Residential 2021",
    image: "/assets/PROJECTSALLPROJECTS/House for Staycation (UK)/PNG image 1.png",
    link: "/gallery/staycation-house",
  },
  {
    id: 9,
    title: "Luxury Gated Community",
    year: "Residential 2022",
    image: "/assets/PROJECTSALLPROJECTS/Luxury Gated Community (Giana Capital)/PNG image 1.png",
    link: "/gallery/luxury-community",
  },
  {
    id: 10,
    title: "Mixed Use Apartment (Astralis)",
    year: "Residential 2023",
    image: "/assets/PROJECTSALLPROJECTS/Mixed use Apartment/PNG image 1.png",
    link: "/gallery/astralis",
  },
  {
    id: 11,
    title: "Private Villa",
    year: "Residential 2023",
    image: "/assets/PROJECTSALLPROJECTS/Private Villa (USA)/PNG image 1.png",
    link: "/gallery/private-villa",
  },
  {
    id: 12,
    title: "Residence #11",
    year: " Residential 2024",
    image: "/assets/PROJECTSALLPROJECTS/Residence 11/PNG image 1.png",
    link: "/gallery/residence11",
  },
  {
    id: 13,
    title: "Residence #622",
    year: "Residential 2021",
    image: "/assets/PROJECTSALLPROJECTS/Residence 622/PNG image 2.png",
    link: "/gallery/residence622",
  },
  {
    id: 14,
    title: "Residence #7 ",
    year: "Residential 2020",
    image: "/assets/PROJECTSALLPROJECTS/Residence 7/PNG image 1.png",
    link: "/gallery/residence7",
  },
  {
    id: 15,
    title: "Sandalwood Villa Interiors",
    year: "Residential 2019",
    image: "/assets/PROJECTSALLPROJECTS/Sandalwood Villa Interiors/PNG image 1.png",
    link: "/gallery/sandalwood",
  },
  {
    id: 16,
    title: "Villa #22",
    year: "Residential 2019",
    image: "/assets/PROJECTSALLPROJECTS/Villa 22/PNG image 1.png",
    link: "/gallery/villa22",
  },
  {
    id: 17,
    title: "Villa #44",
    year: "Residential 2023",
    image: "/assets/PROJECTSALLPROJECTS/Villa 44 (Miami)/PNG image 1.png",
    link: "/gallery/villa44",
  },
  {
    id: 18,
    title: "Villa Entrance",
    year: " Residential 2023",
    image: "/assets/PROJECTSALLPROJECTS/Villa Entrance/PNG image 1.png",
    link: "/gallery/villa-entrance",
  },
];

export default projects;
